### PR TITLE
Update portfolio.css

### PR DESCRIPTION
**Pull request by RAKESH3211**

### CODE REVIEW

**Comment by RAKESH3211** [comment]
sakshi ye kya bol rhi h tu temprary h wo to rakesh
sakshi 14 din rehta h tujhe hoga n tb pta chalega
ese pura sharir nochne ka mn krta haiiiiiii
aur tujhe bs suana haiii

**Comment by RAKESH3211** [comment]
aur ek baat tune kha tha tu yogesh se baat nhi kregi pr tune aaj hi ki 12 ke badd
kyooo???

**Comment by RAKESH3211** [comment]
aur ky sochke ya kya kaam se kiiii

**Comment by RAKESH3211** [comment]
teri yogesh se  kbse hona chalu ho gai sakshi sach btaaa

**Comment by sakshi-294** [comment]
> teri yogesh se kbse hona chalu ho gai sakshi sach btaaa

mne nhi kri ksine bola ki kri mnem nhikrti

**Comment by RAKESH3211** [comment]
meri ksm yogesh se nhi kri tune?

**Comment by RAKESH3211** [comment]
pr hum jb jb ladte h ye kamina bhut jada active ho jata seriously bta de kb se ho rhi as a friend bhi

**Comment by RAKESH3211** [comment]
me literly chale jauga god promise teri life se abhi hi har place se as a frined hi ya dost hi kb se ho rhi bta de me to nhi kru fir tujhe kuch hi hello

**Comment by RAKESH3211** [comment]
even abhi 12. bje ke bad se 12.16 tk bhi hui h ksm se me chalr jauga tum dono ke bich se ksm se me khud tadpa hua hu bs bta de kb se ho rhi

**Pull request closed without merging**
