### PR TITLE
alivdda

### PR DESCRIPTION
**Pull request by romit0312**

### CODE REVIEW

**Comment by romit0312** [comment]
mene jo bhi galti ki pr har ek mistake mani mene gali di ,miss bhevae kiya har kuch kiya har chij ke liye sorry bola aur mana bhi sbke samne apni galti kabhi bhaga nhi jese tu aaj mujhe chord kr bhaag rhi...\

**Comment by romit0312** [comment]
pr itna jarur yad rakh kruga to nhi msg yogesh ho ya koi bhi sathi wo friend ho jada time tk koi person nhi tikegaa me teri  khubsurti se nhi dil se pyar krtaa tha krta hu aur krta rahugaa pe tune bta diya ki jarurat ke time kese piyh dikhai jati h bhale hi wo insan tadap ke mr jaye
sachmuch dil ki baat tujhr lag jaye shyad tujhe kabhi aacha dost ya person nhi milega life mere siva yogesh ho ya mere se bhi aacha kafi aacha wo prson ek limit tk hi sath hoga aaj se 7 sal bhi 
mere jese dil se koi pyar nhi krega sb rup rang dekh kr ya ek need tk hi krege ye baat kuch time baad samjh aayegi 
alvidaa

**Comment by romit0312** [comment]
khusiyo ke time har koi sath hota hai pr jb bura wakt aata h to har koi pith dikhata h
mera aim kisi ko bta kr ye proof krne ka nhi tha ki dekho me bimar hu aur ye bat nhi kr rhi koi devil nhi bna rha thaa
ek patrner ke jese need thi tabhi sbko apni galtiya bta kr tujhse ek support ki umid thi bs.

**Comment by romit0312** [comment]
sb even itna bol rhe ki yarr wo teri stuation tk jaan chuki ki tu kis stuation me h nhi janti hoti to baat alag hoti 
aur har kisi ne kha ki atlest itna to bol deti ki kesa h  ya baad me kr lungi kabhi ya bol deti hamne msg kiya to usko bol do dhyan rakhe man rhe fas gai h pr itni bhi buri stuation to hogi nhi ki ek reply de sake tera jb tu apni galti maan kr bhi itne efforts laga rha to



sakshi sch btau to mere ko mata aai pr fir bhi me nhi chahta ki tera bura ho kabhi ya me tujhe koi baduaa du
bhagwan kre tera hamesha bhala hi ho
byy

**Comment by romit0312** [comment]
tujhe koi fark nhi pad rha dur ja kr bhi pr literly mujhe pad rha h tere se mujhe return me kuch nhi milne pr bhi

**Comment by romit0312** [comment]
pyar me bevafa tu nikli me nhi me is halat me bhi tujhe umid rakh rha hu even pyar kr rha hu tujhse.....
kyo feeling ka mzak bna rhi mere love ki tujhe sb yad h me ra kon dost h kon nhi fir bhi tu mujhe ese time pr chord rhi
jbki sbse jada need mujhe teri h

**Comment by romit0312** [comment]
me tujhe hamesha pyar krta rahuga tu kr nhi krr
tere jesaa nhi hu me 
byy

**Comment by romit0312** [comment]
ek baat yad rakhna sakshi tu abhi gusse me h pr kuch time baad hi tujhe sari duniya me sbse jada yad meri aayegi
kyoki me bhi aaj tadap rha hu.
mera koi aim nnhi tha ki tera social media ya git kharab kru mere pass koi option nhi tha bss

**Comment by romit0312** [comment]
sakshi mujhe meri ksm need h tere sath hi aacha lagta h pls samjh🙏

**Comment by romit0312** [comment]
sakshi tujhe bhi yad mera nature aur kesa h tera bf mafi mannag rha hu🙏🙏🙏

**Comment by romit0312** [comment]
dil se sorry bol rha tujhse ksm se sorry need teri 
rat ek ek bje tk pad rhi pls tab change krke aaja req u sakshi i love u

**Comment by romit0312** [comment]
tujhe bhi pta h me kis type ka ladka hu aur ky niyat h tere liye meri ksm se kabhi tujhe dil se hi pyar krta hu baki ladko jesa nhi hu
sakshi chikenpox ho gya azib hi jal rha h chichida pan etc pls tu as friend hi aaja🙏🙏🙏

**Comment by romit0312** [comment]
qki hamesha se mera dard sirf aur sirf tune samjha h
itne bhi bure nhi h yarr hum dono maaf kr de ab sb samjh gya hu

**Comment by romit0312** [comment]
me har tarah se tujhse mafi mangne ko ready hu 
sakshi log ruth jate h to chord kr chale jate h atlest hum dono to ese nhi h bure time me to sath de sakte h🙏😭

**Comment by romit0312** [comment]
me har place pr mafi manuga tujhse mujhe bhut bura lag rha h mujhe tere kisi koi baat se jalan nhi bs mera pyar tha wo hamesha mera hi rhe bs itni si iksha h ye yogesh , ya koi mujhse aacha dikhne wala n le ja sake qki sidat se pyar kiya h yarr pheli bar koi mzak nhi face se har koi pyar krta h me tujhe dil se krta hu isliye tadpta hu aur tadap rha hu

**Comment by romit0312** [comment]
me har bar tujhe mafi maguga kabhi nazre nhi milauga apni galtiya maan lunga 
sbse phle sbko bta kr mafi manuga ki mene galtiya ki h aur me usse bhut pyar krta hu 
mujhe jha moka milega mafi maguga whtsap, ya kisi clg wale aache bache ke through ya kese bhi mera koi badnaam krne ka aim nni mujhe tujhe shadi krna h to esi ladki se kruga ky jisko badnaam kru

**Comment by romit0312** [comment]
bs mera itna khena h agar rat me late tk pad rhi ya jo bhi kr rhi tu 1 min to msg krke puch sakti h ki kesa h ya mera mood nhi fir kabhi kr lenge dhyan rakhna sb stuation jaan kr bhi esa kr rhi maaf kr de yarr
me tadao gya hu tere liye mata aati h to wish hoti to pura krte h meri wish tu aaja pls dil se wish h

**Comment by romit0312** [comment]
sakshi mujhe nhi yad mere liye tere mind me ky chal rha h wo ab me kesa hu

pr n ek baat gath bandh ke yad rakhna har koi khubsurti ya mtlb se pyar krta h
me hamesha tere dil pe marta hu

**Comment by rakeshs12** [comment]
meri body me ese ese part me dane nikle h n puche mt sajaa to mil rhi h yarr km se km tu to mt de plss

**Pull request closed without merging**
